channels:
  - defaults
  - conda-forge
  - tma-bd
dependencies:
  - python=3.10
  - jupyter>=1.0.0,<1.1
  - matplotlib>=3.8.0,<3.9
  - omegaconf>=2.3.0,<2.4
  - python-dotenv>=1.0.0,<1.1
  - pandas>=2.1.0,<2.2
  - scikit-learn>=1.3.0,<1.4
  - xgboost>=1.7,<1.8
  - numba>=0.57.1,<0.58
  - shap>=0.42.1,<0.43
  - mlflow>=2.7.1,<2.8
platforms:
  - linux-64
